A little RiakCore Book
=======================
LI, Yu
v{{=it.version}}, {{=it.date}}
:doctype: book
:Author: LI, Yu
:Email: liyu1981@gmail.com
:Date: {{=it.date}}
:Revision: {{=it.version}}


[dedication]
For What and For Whom
---------------------

WARNING: You have probably arrived at the wrong place, and are planning to
spend sometime on something you will be not interested.  So let us check
whether we should leave.

*For What*

This little book is about https://github.com/basho/riak_core[RiakCore], which
is an application framework for building distributed, scalable, fault-tolerant
applications. RiakCore is written in http://www.erlang.org[Erlang] programming
language, open sourced by http://www.basho.com[Basho Technologies].  The
application built with RiakCore, is usually for serving purpose, which is
called server. Being different from what you use on your PC or phone, server
should never stop, be always available, and be able to recover from really bad
disasters. So it is believed that servers are much harder to be done right. If
you are willing to write this kind of serious applications, you can stay.

*For Whom*

Serious programmers write servers never going down. With years of experience in
backend programming, they have done enough of thinking on how to distribute the
computing to nodes in clusters, make everything scalable, and restore state
before bringing some crashed nodes back. Lots of programs in lots of
programming languages have been done, while hundreds of thousands of lines of
code have made the fun parts vanished. Then they learned some Erlang, and other
cool stuff such as
http://www.erlang.org/doc/design_principles/users_guide.html[OTP], and they
want to resolve these problems again in a more elegant, understandable way, and
most importantly, bring the fun parts back.  In short, if you have questions in
how to elegantly write an always-up, instantly-scalable server, you can stay.

{zwsp} +

But be not scared by me. :-)

{zwsp} +

As long as you are interested in writing some cool server stuff, you are
welcome! RiakCore is made to ease the process of making something distributed
cool. Geeks love it and think it the next-big-thing in field of server
programming. But not everyone is geek. So in this book, I will make my best to
explain the concept and practice of programming RiakCore, in language that
everyone can follow and understand.

NOTE: But I am serious in the Erlang part. For reading this
book, you would better to be familar with writting Erlang
programs. If you are not, I know an excellent book for you to read. Its name is
http://learnyousomeerlang.com[Learn Your Some Erlang for great good!], or
shortly LYSE. Throughout this book, I will frequently reference LYSE, whenever
there is some Erlang stuff we would better to be aware of.
