A little RiakCore Book
=======================
LI, Yu (liyu1981@gmail.com)
v{{=it.version}}, {{=it.date}}
:doctype: book
:Author:    LI, Yu
:Email:     liyu1981@gmail.com
:Date:      {{=it.date}}
:Revision:  {{=it.version}}


[dedication]
For What and For Whom
---------------------

Attention! Your probably arrive the wrong place, and are planning
spend sometime on something you are not interested and not familiar.
So let us check whether we should leave.

*For What*

This little book is about https://github.com/basho/riak_core[RiakCore], which
is an application framework for building distributed, scalable, fault-tolerant
applications. RiakCore is written in http://www.erlang.org[Erlang]
programming language, open sourced by http://www.basho.com[Basho
Technologies].  The application built with RiakCore, is usually for
serving purpose. Being different from what you use on your PC or
phone, application for serving should never stop, be always available,
and recover from some really bad disasters. So if you are willing to
write servers, you can stay.

*For Whom*

Serious programmers who write servers never go down. With years of
experience in backend programming, you have done enough of thinking
how to distribute the computing to nodes in server clusters, make the
storage scalable, and clean up this and that before bringing some
crashed nodes back. And you know bit of Erlang, and other cool stuff.
In short, if you have questions in how to write an always-up service,
you can stay.

NOTE: Do not scared by me, but except the Erlang part. For reading this
book, you have to at least be familar with how to write Erlang
programs. If you are not, one of the excellent book is
http://learnyousomeerlang.com[LYSE].
